version: '3.3'

services:
  #service 1: definition of mysql database
  db:
    image: mysql:latest
    hostname: mysql-patrimonydb
    container_name: mysql-patrimonydb
    environment:
      - MYSQL_ROOT_PASSWORD=patrimony



    ports:
      - "3308:3308"
    restart: always





  #service 3: definition of your spring-boot app
  customerservice:                        #it is just a name, which will be used only in this file.
    image: patrimonyback_image              #name of the image after dockerfile executes
    container_name: patrimonyback_container      #name of the container created from docker image
    build:
      context: ./                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8081:8081"                       #docker containter port with your os port
    restart: always

    depends_on:                           #define dependencies of this app
      - db      #dependency name (which is defined with this name 'db' in this file earlier)
    command: sh -c './wait-for db:3308 -- npm start'
    links:
      - db:app_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-patrimonydb:3308/patrimonybd?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: patrimony



